controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
  - name: fake_robot_wrist_controller
    type: $(arg fake_execution_type)
    joints:
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_rotot_total_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses per group
  - group: rotot_total
    pose: stand_up_face_down